// Generated by diesel_ext

use super::schema::{images, mansions};
use diesel::prelude::*;

#[derive(Queryable, Identifiable, Selectable, Debug, PartialEq)]
#[diesel(table_name = mansions)]
pub struct Mansion {
    pub id: i32,
    pub address: String,
    pub price: String,
    pub size: String,
    pub bedrooms: i32,
    pub bathrooms: i32,
    pub receptions: i32,
    pub type_: String,
}

#[derive(Queryable, Selectable, Identifiable, Associations, Debug, PartialEq)]
#[diesel(belongs_to(Mansion))]
#[diesel(table_name = images)]
pub struct Image {
    pub id: i32,
    pub image_path: String,
    pub mansion_id: i32,
}

#[derive(Insertable)]
#[diesel(table_name = mansions)]
pub struct NewMansion {
    pub address: String,
    pub price: String,
    pub size: String,
    pub bedrooms: i32,
    pub bathrooms: i32,
    pub receptions: i32,
    pub type_: String,
}
