// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use super::schema::mansionees;
use diesel::prelude::*;
#[derive(Queryable, Selectable, Debug, Insertable)]
#[diesel(table_name = mansionees)]
pub struct Mansionee {
    pub id: i32,
    pub address: String,
    pub price: Option<i32>,
    pub size: Option<f64>,
    pub bedrooms: Option<i32>,
    pub bathrooms: Option<i32>,
    pub receptions: Option<i32>,
    pub house_type: String,
    pub pictures: Option<serde_json::Value>,
}
