/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllMansions: typeof import('./components/mansion/AllMansions.vue')['default']
    AppFooter: typeof import('./components/navigation/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginFIXME: typeof import('./components/user/LoginFIXME.vue')['default']
    MansionInfo: typeof import('./components/mansion/MansionInfo.vue')['default']
    NavBar: typeof import('./components/navigation/NavBar.vue')['default']
    RegisterFIXME: typeof import('./components/user/RegisterFIXME.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
